import { useEffect, useState } from "react";
import { Line, LineChart, CartesianGrid, Tooltip, XAxis, YAxis } from "recharts";
import { CalendarDays, Info } from "lucide-react";
import { buildSubscriptionStoryFacts, type CalculationResult, type Decision } from "../domain";
import { formatMoney } from "../domain/format";
import { useAppStore } from "../store";
import { NumericEditor } from "./NumericEditor";
import { Badge, Card, Input } from "./ui";

export function SubscriptionComparison({ decision, calculation }: { decision: Decision; calculation: CalculationResult }) {
  const months = decision.comparisonMonths ?? 12;
  const setComparisonMonths = useAppStore((state) => state.setComparisonMonths);
  const [draft, setDraft] = useState(String(months));
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { setDraft(String(months)); setError(null); }, [months]);
  const commitWindow = () => {
    const value = /^\d+$/.test(draft.trim()) ? Number(draft) : NaN;
    if (!Number.isInteger(value) || value < 1 || value > 120) {
      setError(`Enter a whole number from 1 to 120. Results still use the ${months}-month window.`);
      return;
    }
    setComparisonMonths(value);
    setError(null);
  };
  return <section className="mt-8" aria-labelledby="subscription-cost-title">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-start"><div className="max-w-2xl"><p className="section-label">Compare actual payments</p><h2 id="subscription-cost-title" className="display mt-2 text-3xl font-extrabold text-ink">See what each plan costs.</h2><p className="mt-2 text-sm leading-6 text-muted">Enter each plan's payment amount. The comparison counts the full payment whenever a new billing period begins.</p></div><Card className="w-full p-4 md:max-w-64"><label htmlFor="comparison-months" className="text-sm font-bold text-ink">Comparison window</label><div className="mt-2 flex items-center gap-2"><Input id="comparison-months" inputMode="numeric" value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={commitWindow} onKeyDown={(event) => { if (event.key === "Enter") event.currentTarget.blur(); }} aria-invalid={!!error} aria-describedby="comparison-window-help" /><span className="text-xs font-semibold text-muted">months</span></div><p id="comparison-window-help" className="mt-2 text-xs leading-5 text-muted">{decision.comparisonMonths === undefined ? "Default: 12 months. Edit this window to explore a shorter or longer period." : "An editable comparison setting, not a prediction of how long you will use either plan."}</p>{error && <p role="alert" className="mt-2 text-xs leading-5 text-red-600">{error}</p>}</Card></div>
    <div className="mt-5 grid gap-5 md:grid-cols-2">{decision.options.map((option, index) => {
      const costs = option.subscriptionCosts;
      const result = calculation.status === "subscription" ? calculation.options[index] : null;
      const unusedCoverage = result ? result.coverageMonths - months : 0;
      return <Card key={option.id} className="overflow-hidden"><div className={`h-1.5 ${index === 0 ? "bg-near" : "bg-far"}`} /><div className="p-5 sm:p-6"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><h3 className={`text-xl font-bold ${index === 0 ? "text-near" : "text-far"}`}>{option.name}</h3>{costs && <Badge>{costs.periodMonths === 1 ? "Paid monthly" : costs.periodMonths === 12 ? "Paid annually" : `Paid every ${costs.periodMonths} months`}</Badge>}</div>{costs && <NumericEditor label={costs.periodMonths === 12 ? "Annual payment" : costs.periodMonths === 1 ? "Monthly payment" : `Payment for ${costs.periodMonths} months`} field={costs.paymentCents} path={["options", index, "subscriptionCosts", "paymentCents"]} unit="USD / payment" scale={100} />}{result && <div className="mt-5 border-t border-line pt-5"><p className="text-xs font-semibold text-muted">Total paid over {months} {months === 1 ? "month" : "months"}</p><p className="number mt-2 text-3xl font-extrabold text-ink">{formatMoney(result.totalCostCents)}</p><p className="mt-2 text-xs leading-5 text-muted">{result.paymentCount} {result.paymentCount === 1 ? "payment" : "payments"} · {result.coverageMonths} {result.coverageMonths === 1 ? "month" : "months"} covered</p>{unusedCoverage > 0 && <p className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-800">{unusedCoverage} prepaid {unusedCoverage === 1 ? "month extends" : "months extend"} beyond this window. Unused coverage is not refunded in this comparison.</p>}</div>}</div></Card>;
    })}</div>
    {calculation.status === "invalid" && <Card className="mt-5 border-amber-200 bg-amber-50 p-5"><div className="flex items-start gap-3"><Info size={20} className="mt-0.5 shrink-0 text-amber-600" /><div><h3 className="text-sm font-bold text-ink">Complete the payment amounts</h3><ul className="mt-2 list-disc space-y-1 pl-4 text-sm leading-6 text-amber-800">{calculation.issues.map((issue, index) => <li key={`${issue.path}-${index}`}>{issue.message}</li>)}</ul></div></div></Card>}
    {calculation.status === "subscription" && <Card className="mt-5 p-5 sm:p-7"><div className="flex items-start gap-3"><CalendarDays size={21} className="mt-1 shrink-0 text-near" /><div><p className="section-label">Payments over time</p><h3 className="mt-2 text-lg font-bold leading-7 text-ink">{buildSubscriptionStoryFacts(decision, calculation).subscriptionCostComparison}</h3><p className="mt-2 text-xs leading-5 text-muted">Month 0 is before the first payment. Each step includes the full charge for the next billing period.</p></div></div><div className="mt-6 h-72 min-w-0 w-full" role="img" aria-label={`Cumulative payments over ${months} months: ${decision.options.map((option, index) => `${option.name} ${formatMoney(calculation.options[index].totalCostCents)}`).join(", ")}.`}><LineChart responsive style={{ width: "100%", height: "100%", minWidth: 0 }} data={calculation.timeline} margin={{ top: 8, right: 16, bottom: 26, left: 8 }}><CartesianGrid stroke="#edf1f6" /><XAxis dataKey="month" type="number" domain={[0, months]} allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#738298", fontSize: 11 }} label={{ value: "Comparison month", position: "insideBottom", offset: -16, fill: "#738298", fontSize: 12 }} /><YAxis tickLine={false} axisLine={false} width={70} tick={{ fill: "#738298", fontSize: 11 }} tickFormatter={(value: number) => `$${(value / 100).toLocaleString("en-US", { notation: "compact", maximumFractionDigits: 1 })}`} /><Tooltip labelFormatter={(value) => `Month ${value}`} formatter={(value) => formatMoney(Number(value))} contentStyle={{ borderRadius: 12, border: "1px solid #e2e8f0", fontSize: 12 }} /><Line type="stepAfter" dataKey="optionACostCents" name={decision.options[0].name} stroke="#3f68ef" strokeWidth={3} dot={false} isAnimationActive={false} /><Line type="stepAfter" dataKey="optionBCostCents" name={decision.options[1].name} stroke="#13a99b" strokeWidth={3} dot={false} isAnimationActive={false} /></LineChart></div><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted">{decision.options.map((option, index) => <span key={option.id}><i className={`mr-1.5 inline-block h-2 w-2 rounded-full ${index === 0 ? "bg-near" : "bg-far"}`} />{option.name}</span>)}</div><p className="mt-5 border-t border-line pt-4 text-xs leading-5 text-muted">This model renews each plan at the entered price for as long as the comparison window needs coverage. Refunds, cancellation penalties, price changes and usage frequency are not included.</p></Card>}
  </section>;
}
