import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, Compass, GitCompareArrows, Layers3, Pencil, Plus, RotateCcw, ScanText, ShieldCheck, Sparkles, Target, Wallet, X } from "lucide-react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge, Button, Card } from "../components/ui";
import { calculateChoice, formatMoney, formatValue } from "./engine";
import { makeDemo, makeManualDecision } from "./fixtures";
import { analyzeMaterials, generateChoice } from "./api";
import { colors, freshId, OptionEditor, unknownValue, userValue, ValueEditor, type EditDecision } from "./editors";
import { FactorSection } from "./FactorSection";
import { MaterialsPanel } from "./MaterialsPanel";
import type { ChoiceCalculation, ChoiceDecision, ChoiceOption, Currency, MaterialAnalysis, OptionCalculation } from "./types";
import "./choice.css";

type Screen = "input" | "review" | "compare";
type Change = { label: string; optionId?: string; before: ChoiceCalculation; previousDecision: ChoiceDecision };
const money = (value: number | null, decision: ChoiceDecision) => formatMoney(value, decision.currency);
const time = (value: number | null) => value === null ? "Unknown" : `${new Intl.NumberFormat("en-US", { maximumFractionDigits: 1 }).format(value / 60)} hr`;
const modeText = { demo: "Fictional example", live: "Live AI interpretation", manual: "Your manual comparison" };
const comparisonTitles: Record<ChoiceCalculation["comparison"]["status"], string> = { preferred: "A clearer fit for your priorities", tie: "A tie on what matters most", insufficient: "A few details could change the choice", no_feasible: "None meet your current requirements", unranked: "The tradeoffs, side by side" };

function Header({ screen, onNavigate, hasDecision }: { screen: Screen; onNavigate: (screen: Screen) => void; hasDecision: boolean }) {
  return <header className="cc-header"><div className="cc-wrap cc-header-inner"><button className="cc-brand" aria-label="Clear Choice home" onClick={() => onNavigate("input")}><span className="cc-logo"><GitCompareArrows size={22} /></span><span>clear<span>choice</span><b>.</b></span></button><nav aria-label="Decision progress">{(["input", "review", "compare"] as const).map((step, index) => <button key={step} disabled={step !== "input" && !hasDecision} aria-current={screen === step ? "step" : undefined} onClick={() => onNavigate(step)}><span>{index + 1}</span>{["Describe", "Make it yours", "Compare"][index]}{index < 2 && <ChevronRight size={13} />}</button>)}</nav><Badge className="bg-teal-50 text-teal-800">Local workspace</Badge></div></header>;
}

function Entry({ onLoad, existing, onResume }: { onLoad: (decision: ChoiceDecision, screen?: Screen) => void; existing: ChoiceDecision | null; onResume: () => void }) {
  const [mode, setMode] = useState<"decision" | "material">("decision");
  const [description, setDescription] = useState("");
  const [material, setMaterial] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const controller = useRef<AbortController | null>(null);
  useEffect(() => () => controller.current?.abort(), []);
  async function generate() {
    if (!description.trim()) return;
    controller.current?.abort(); const abort = new AbortController(); controller.current = abort;
    setBusy(true); setError("");
    try { const result = await generateChoice(description.trim(), abort.signal); if (!abort.signal.aborted) onLoad(result); }
    catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) setError(error instanceof Error ? error.message : "Could not understand the decision. Please try again."); }
    finally { if (!abort.signal.aborted) setBusy(false); }
  }
  const manual = () => { const decision = makeManualDecision(); if (description.trim()) { decision.originalInput = description.trim(); decision.description = description.trim().slice(0, 4000); } onLoad(decision); };
  const fromMaterial = () => {
    const decision = makeManualDecision(); decision.title = "Understand this offer"; decision.description = "Review the supplied information, then compare it with an alternative or waiting.";
    decision.options[0].name = "Offer to review"; decision.options[1].name = "Alternative / wait";
    decision.options[0].materials.push({ id: freshId("material"), title: "Pasted information", text: material.trim() }); onLoad(decision);
  };
  return <main className="cc-wrap cc-entry">
    <section className="cc-hero"><div><div className="cc-kicker"><span /> Room to think. Space to choose.</div><h1>A choice that fits<br /><em>your actual life.</em></h1><p>See the costs, commitments, and everyday tradeoffs behind your next decision. Change the details. Find what matters to you.</p><div className="cc-hero-points"><span><CheckCircle2 size={15} /> Your priorities first</span><span><CheckCircle2 size={15} /> No made-up scores</span><span><CheckCircle2 size={15} /> No ad required</span></div></div><div className="cc-hero-art" aria-hidden="true"><div className="cc-art-label"><Compass size={18} /> TWO WAYS FORWARD</div><div className="cc-art-paths"><div><span className="cc-art-letter">A</span><span className="cc-art-line" /><div className="cc-art-stub"><Wallet size={17} /><span /><span /></div><div className="cc-art-stub"><Clock3 size={17} /><span /><span /></div></div><div><span className="cc-art-letter">B</span><span className="cc-art-line" /><div className="cc-art-stub"><Wallet size={17} /><span /><span /></div><div className="cc-art-stub"><Clock3 size={17} /><span /><span /></div></div></div><div className="cc-art-caption"><Target size={16} /> A little clarity before you commit.</div></div></section>
    <Card className="cc-entry-card"><div className="cc-entry-tabs" role="tablist" aria-label="Start a task"><button role="tab" aria-selected={mode === "decision"} onClick={() => setMode("decision")}><GitCompareArrows size={18} /> Help me choose</button><button role="tab" aria-selected={mode === "material"} onClick={() => setMode("material")}><ScanText size={18} /> Check this information</button></div>
      {mode === "decision" ? <div className="cc-entry-body"><label htmlFor="choice-description"><h2>What are you deciding?</h2><p>Write it in your own words. Include any needs, options, or numbers you already know.</p></label><textarea id="choice-description" rows={4} maxLength={8000} value={description} onChange={e => setDescription(e.target.value)} placeholder="Should I repair my laptop or buy a new one? I need it for classes and want to spend no more than $800." disabled={busy} />
        {error && <p className="cc-error" role="alert">{error}</p>}
        <div className="cc-entry-actions"><Button variant="ghost" onClick={manual} disabled={busy}><Pencil size={16} /> Build a manual comparison</Button><Button variant="blue" onClick={generate} disabled={!description.trim() || busy}><Sparkles size={16} />{busy ? "Understanding your decision…" : "Explore my options"}<ArrowRight size={16} /></Button></div>
        {busy ? <div className="cc-row"><p className="cc-hint" role="status">Nemotron is interpreting your goals and suggesting factors. This may take a minute.</p><Button variant="ghost" size="sm" onClick={() => { controller.current?.abort(); setBusy(false); }}>Cancel</Button></div> : <p className="cc-hint">English or Chinese input. AI proposes; you review. Missing numbers stay unknown.</p>}
      </div> : <div className="cc-entry-body"><label htmlFor="material-entry"><h2>Give the words a closer look.</h2><p>Paste an ad, sales chat, quote, or terms. Review the evidence, then add it to a decision.</p></label><textarea id="material-entry" rows={5} maxLength={12000} value={material} onChange={e => setMaterial(e.target.value)} placeholder="Paste the original information here…" /><div className="cc-entry-actions"><span className="cc-hint">Text only in this version · attached to one option</span><Button variant="blue" disabled={!material.trim()} onClick={fromMaterial}>Start material review <ArrowRight size={16} /></Button></div></div>}
    </Card>
    {existing && <button className="cc-resume" onClick={onResume}>Resume “{existing.title}” <ArrowRight size={15} /></button>}
    <section className="cc-examples"><div className="cc-section-head"><div><p className="cc-eyebrow">Get a feel for it</p><h2>Try a fictional example</h2></div><span>Editable demo data · no model call</span></div><div className="cc-example-grid">{([{ id: "gym", icon: "↻", name: "Monthly or annual?", detail: "Membership cost & flexibility", color: "blue" }, { id: "housing", icon: "⌂", name: "Which place fits?", detail: "Rent, commute & a pet", color: "teal" }, { id: "laptop", icon: "⌘", name: "Repair or replace?", detail: "Upfront cost & useful details", color: "violet" }, { id: "course", icon: "◷", name: "Which course?", detail: "Schedule, workload & goals", color: "amber" }] as const).map(example => <button key={example.id} data-testid={`demo-${example.id}`} onClick={() => onLoad(makeDemo(example.id), "compare")}><span className={`cc-example-icon ${example.color}`}>{example.icon}</span><strong>{example.name}</strong><small>{example.detail}</small><ArrowRight size={16} /></button>)}</div></section>
    <div className="cc-entry-note"><ShieldCheck size={16} /><span>Your edits calculate locally. AI runs only when you ask for it.</span></div>
  </main>;
}

function ContextEditor({ decision, edit }: { decision: ChoiceDecision; edit: EditDecision }) {
  return <section className="cc-context"><div className="cc-section-head"><div><p className="cc-eyebrow">Shared across every option</p><h2>Your current conditions</h2></div><Badge className="bg-teal-50 text-teal-800"><span className="cc-dot" /> Recalculates instantly</Badge></div><div className="cc-context-fields"><ValueEditor label="Planning horizon" value={decision.context.months} unit="whole months" min={1} max={120} step="1" onChange={value => edit("Planning horizon", copy => { copy.context.months = value; })} /><ValueEditor label="Uses per month" value={decision.context.usesPerMonth} unit="uses / month" onChange={value => edit("Usage frequency", copy => { copy.context.usesPerMonth = value; })} /><ValueEditor label="Total budget (optional)" value={decision.context.budgetCents} type="money" unit={`${decision.currency} · entire horizon`} scale={100} step="0.01" onChange={value => edit("Total budget", copy => { copy.context.budgetCents = value; })} /></div><p className="cc-hint">A supplied budget is a must-meet limit over this horizon. Fixed-fee plans do not become cheaper with fewer visits; only their cost per use changes.</p></section>;
}

function AssumptionEditor({ text, index, onSave, onRemove }: { text: string; index: number; onSave: (text: string) => void; onRemove: () => void }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(text);
  return <div className="cc-goal cc-assumption"><div>{editing ? <><label className="cc-field"><span>Qualitative assumption</span><textarea aria-label={`Edit assumption ${index + 1} text`} maxLength={1000} rows={3} value={draft} onChange={event => setDraft(event.target.value)} /></label><div className="cc-wrap-row"><Button variant="subtle" size="sm" disabled={!draft.trim()} onClick={() => { onSave(draft.trim()); setEditing(false); }}>Save assumption</Button><Button variant="ghost" size="sm" onClick={() => setEditing(false)}>Cancel</Button></div></> : <><p>{text}</p><small>Assumption / possibility · not a calculated fact</small></>}</div>{!editing && <Button variant="ghost" size="icon" aria-label={`Edit assumption ${index + 1}`} onClick={() => { setDraft(text); setEditing(true); }}><Pencil size={13} /></Button>}<Button variant="ghost" size="icon" aria-label={`Remove assumption ${index + 1}`} onClick={onRemove}><X size={14} /></Button></div>;
}

function DecisionNotes({ decision, edit }: { decision: ChoiceDecision; edit: EditDecision }) {
  const [newGoal, setNewGoal] = useState("");
  const [assumption, setAssumption] = useState("");
  return <div className="cc-notes-grid"><section className="cc-notes"><h3><Target size={17} /> What you want from this choice</h3>{decision.goals.length === 0 && <p className="cc-hint">Add a goal or turn it into a factor below.</p>}{decision.goals.map((goal, index) => <div className="cc-goal" key={index}><div><p>{goal.text}</p><small>{goal.source === "user_input" ? "Your stated goal" : "AI suggestion · confirm or remove"}{goal.quote ? ` · “${goal.quote}”` : ""}</small></div>{goal.source === "model_suggestion" && <Button variant="ghost" size="icon" aria-label={`Confirm goal ${goal.text}`} onClick={() => edit("Confirmed goal", copy => { copy.goals[index].source = "user_input"; copy.goals[index].quote = copy.goals[index].text; })}><Check size={15} /></Button>}<Button variant="ghost" size="icon" aria-label={`Remove goal ${goal.text}`} onClick={() => edit("Removed goal", copy => { copy.goals.splice(index, 1); })}><X size={14} /></Button></div>)}<div className="cc-row"><input aria-label="New decision goal" maxLength={2000} placeholder="Add your own goal…" value={newGoal} onChange={e => setNewGoal(e.target.value)} /><Button variant="ghost" size="icon" aria-label="Add goal" disabled={!newGoal.trim() || decision.goals.length >= 20} onClick={() => { edit("Added goal", copy => { copy.goals.push({ text: newGoal.trim(), source: "user_input", quote: newGoal.trim() }); }); setNewGoal(""); }}><Plus size={17} /></Button></div></section><section className="cc-notes"><h3><Compass size={17} /> Assumptions & possibilities</h3><p className="cc-hint">Qualitative possibilities do not change numbers automatically. If you expect a change in usage, enter that estimate in the shared conditions.</p>{decision.assumptions.map((item, index) => <AssumptionEditor key={index} text={item} index={index} onSave={text => edit("Updated qualitative assumption", copy => { copy.assumptions[index] = text; })} onRemove={() => edit("Removed assumption", copy => { copy.assumptions.splice(index, 1); })} />)}<div className="cc-row"><input aria-label="New assumption" maxLength={1000} placeholder="For example, I may visit less after moving" value={assumption} onChange={e => setAssumption(e.target.value)} /><Button variant="ghost" size="icon" aria-label="Add assumption" disabled={!assumption.trim() || decision.assumptions.length >= 20} onClick={() => { edit("Added qualitative assumption", copy => { copy.assumptions.push(assumption.trim()); }); setAssumption(""); }}><Plus size={17} /></Button></div></section></div>;
}

function Impact({ change, result, decision, comparison }: { change: Change; result: OptionCalculation; decision: ChoiceDecision; comparison: ChoiceCalculation["comparison"] }) {
  const before = change.before.options.find(option => option.optionId === result.optionId);
  if (!before) return null;
  const costChanged = before.totalCostCents !== result.totalCostCents;
  const timeChanged = before.totalMinutes !== result.totalMinutes;
  const unitChanged = before.costPerUseCents !== result.costPerUseCents;
  const eligibilityChanged = before.eligibility !== result.eligibility;
  const recommendationChanged = change.before.comparison.status !== comparison.status || change.before.comparison.preferredIds.join() !== comparison.preferredIds.join();
  const factorsChanged = decision.factors.filter(factor => before.factorValues[factor.id]?.value !== result.factorValues[factor.id]?.value);
  const direct = [costChanged ? `Total cost: ${money(before.totalCostCents, decision)} → ${money(result.totalCostCents, decision)}` : "", timeChanged ? `Tracked time: ${time(before.totalMinutes)} → ${time(result.totalMinutes)}` : "", unitChanged ? `Cost per use: ${money(before.costPerUseCents, decision)} → ${money(result.costPerUseCents, decision)}` : "", ...factorsChanged.filter(factor => !factor.ruleId).map(factor => `${factor.name}: ${formatValue(factor, result.factorValues[factor.id] ?? unknownValue(), decision.currency)}`)].filter(Boolean);
  return <section className="cc-impact"><h4><Layers3 size={14} /> What this change does</h4><div className="cc-chain"><div><span>Changed factor</span><p>{change.label}{change.optionId && change.optionId !== result.optionId ? " · another option" : ""}</p></div><ArrowDown size={13} /><div><span>Direct effect</span><p>{direct.length ? direct.join(". ") : "No change to this option’s calculated cost, time, or factor values."}</p></div><ArrowDown size={13} /><div><span>What follows</span><p>{eligibilityChanged ? `Eligibility changed from ${before.eligibility} to ${result.eligibility}.` : "Requirement status stays the same."} {recommendationChanged ? "The overall comparison changed." : "The overall comparison stays the same."}</p></div></div><p className="cc-hint">Unchanged: {[!costChanged ? "total cost" : "", !timeChanged ? "tracked time" : "", !unitChanged ? "cost per use" : "", !eligibilityChanged ? "eligibility" : ""].filter(Boolean).join(", ") || "none of the tracked metrics"}. Uncertain lifestyle effects are not inferred.</p></section>;
}

function OptionCard({ decision, option, result, index, calculation, edit, change, analysis, busy, error, analyze }: { decision: ChoiceDecision; option: ChoiceOption; result: OptionCalculation; index: number; calculation: ChoiceCalculation; edit: EditDecision; change: Change | null; analysis?: MaterialAnalysis; busy: boolean; error?: string; analyze: () => void }) {
  const maxCost = Math.max(...calculation.options.map(item => item.totalCostCents ?? 0), 1);
  const maxTime = Math.max(...calculation.options.map(item => item.totalMinutes ?? 0), 1);
  const preferred = calculation.comparison.preferredIds.includes(option.id);
  const eligibility = { eligible: "Meets known requirements", pending: "Requirements need checking", ineligible: "Does not meet requirements" };
  return <article className={`cc-option-card ${preferred ? "cc-preferred" : ""}`} style={{ "--option-color": colors[index % colors.length] } as React.CSSProperties} data-testid={`option-${index}`}><div className="cc-option-card-head"><div className="cc-row"><span className="cc-option-letter">{String.fromCharCode(65 + index)}</span><span className="cc-eyebrow">Your option</span>{preferred && <Badge className="cc-fit-badge">{calculation.comparison.status === "tie" ? "Tied on primary preference" : "Current fit"}</Badge>}</div><h2>{option.name}</h2><p>{option.description}</p><span className={`cc-eligibility ${result.eligibility}`}><span />{eligibility[result.eligibility]}</span></div>
    <div className="cc-option-body"><div className="cc-main-metric"><span>Total for {decision.context.months.value ?? "?"} months</span><strong data-testid={`total-${index}`}>{money(result.totalCostCents, decision)}</strong><small>{option.costsComplete && option.costs.length > 0 ? "Complete charge list · actual payment timing" : "Incomplete charges · total stays unknown"}</small></div><div className="cc-mini-metrics"><div><Wallet size={15} /><span>First payment</span><strong>{money(result.firstPaymentCents, decision)}</strong></div><div><RotateCcw size={15} /><span>Per use</span><strong>{money(result.costPerUseCents, decision)}</strong></div><div><Clock3 size={15} /><span>Time / month</span><strong>{time(result.monthlyMinutes)}</strong></div></div>
      <div className="cc-mini-chart" role="img" aria-label={`${option.name}: total cost ${money(result.totalCostCents, decision)}, tracked time ${time(result.totalMinutes)}. Scales are shared across options.`}><div><span>Cost over horizon</span><b>{money(result.totalCostCents, decision)}</b></div><div className="cc-bar-track"><span style={{ width: result.totalCostCents === null ? "0" : `${100 * result.totalCostCents / maxCost}%` }} /></div><div><span>Tracked time over horizon</span><b>{time(result.totalMinutes)}</b></div><div className="cc-bar-track cc-bar-time"><span style={{ width: result.totalMinutes === null ? "0" : `${100 * result.totalMinutes / maxTime}%` }} /></div><small>Same scale across cards for each metric. Unknowns have no bar.</small></div>
      <div className="cc-requirements">{result.failed.map(item => <p className="cc-error" key={item}>{item}</p>)}{result.unknown.map(item => <p className="cc-warning" key={item}>{item}</p>)}{decision.factors.filter(factor => factor.optionIds.includes(option.id)).slice(0, 5).map(factor => <div key={factor.id}><span>{factor.name}<small>{factor.purpose === "hard" ? "Must meet" : factor.id === decision.primaryFactorId ? "Primary preference" : factor.purpose === "preference" ? "Tradeoff" : "Reference"}</small></span><strong title={result.factorValues[factor.id]?.note}>{formatValue(factor, result.factorValues[factor.id] ?? unknownValue(), decision.currency)}</strong></div>)}</div>
      {change && <Impact change={change} result={result} decision={decision} comparison={calculation.comparison} />}
      <section className="cc-story"><div className="cc-subheading"><h3>Your life with this choice</h3><Badge>Calculated summary</Badge></div>{([{ key: "start", title: "At the start", icon: Wallet }, { key: "routine", title: "Your everyday routine", icon: Clock3 }, { key: "horizon", title: "Over your planning horizon", icon: Layers3 }, { key: "reconsider", title: "When to reconsider", icon: RotateCcw }] as const).map(({ key, title, icon: Icon }) => <div className="cc-story-moment" key={key}><span><Icon size={15} /></span><div><h4>{title}</h4><p>{result.summary[key]}</p></div></div>)}<p className="cc-hint">Numbers use this exact decision version. Qualitative effects are not predictions of happiness, health, or success.</p></section>
      <details className="cc-detail"><summary><Pencil size={15} /> Edit this option <span>Charges, timing & sources</span></summary><OptionEditor option={option} currency={decision.currency} index={index} onChange={(next, label) => edit(label, copy => { copy.options[copy.options.findIndex(item => item.id === option.id)] = next; }, option.id)} /></details>
      <MaterialsPanel decision={decision} option={option} analysis={analysis} busy={busy} error={error} edit={edit} onAnalyze={analyze} />
      {result.issues.length > 0 && <details className="cc-detail cc-data-notes"><summary>Data to confirm <span>{result.issues.length} note(s)</span></summary>{result.issues.map(issue => <p key={issue} className="cc-hint">{issue}</p>)}</details>}
    </div>
  </article>;
}

function CostChart({ decision, calculation }: { decision: ChoiceDecision; calculation: ChoiceCalculation }) {
  const [projection, setProjection] = useState(false);
  const projected = useMemo(() => projection ? calculateChoice({ ...decision, context: { ...decision.context, months: userValue(Math.max(12, typeof decision.context.months.value === "number" ? decision.context.months.value : 12)) } }) : calculation, [decision, calculation, projection]);
  const count = Math.max(...projected.options.map(option => option.cumulativeCosts.length), 0);
  const data = Array.from({ length: count }, (_, index) => Object.fromEntries([["month", index + 1], ...projected.options.map(option => [`option_${option.optionId}`, option.cumulativeCosts[index]?.costCents === null || option.cumulativeCosts[index]?.costCents === undefined ? null : option.cumulativeCosts[index].costCents! / 100])]));
  const anyKnown = data.some(row => Object.entries(row).some(([key, value]) => key !== "month" && value !== null));
  const markers = calculation.breakEven.filter(point => point.month <= count).slice(0, 4);
  return <section className="cc-chart-panel"><div className="cc-section-head"><div><p className="cc-eyebrow">See how the commitment builds</p><h2>Cumulative spending</h2><p>{projection ? "Projection through at least 12 months, using the same current prices and usage. Your selected comparison horizon is unchanged." : "Actual payment timing, with annual fees paid at the start of each year."}</p></div><label className="cc-checkbox"><input type="checkbox" checked={projection} onChange={e => setProjection(e.target.checked)} /> Show 12-month projection</label></div>
    <div className="cc-chart-legend">{decision.options.map((option, index) => <span key={option.id}><i style={{ backgroundColor: colors[index % colors.length] }} />{option.name}</span>)}</div>
    {anyKnown ? <div className="cc-chart" role="img" aria-label={`Cumulative spending over ${count} months in ${decision.currency}. The data table below contains exact values.`}><ResponsiveContainer width="100%" height={270}><LineChart data={data} margin={{ top: 25, right: 35, bottom: 12, left: 15 }}><CartesianGrid vertical={false} stroke="#e9edf3" /><XAxis dataKey="month" tick={{ fontSize: 11 }} tickLine={false} axisLine={false} label={{ value: "Month", position: "insideBottomRight", offset: -6, fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} tickLine={false} axisLine={false} width={65} tickFormatter={value => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(Number(value))} label={{ value: decision.currency, position: "insideTopLeft", offset: -15, fontSize: 11 }} /><Tooltip formatter={(value, name) => [formatMoney(Number(value) * 100, decision.currency), name]} labelFormatter={label => `Month ${label}`} />{markers.map(point => <ReferenceLine key={`${point.month}-${point.kind}`} x={point.month} stroke="#b5bece" strokeDasharray="4 4" label={{ value: point.kind === "tie" ? "Cost tie" : "Cost order changes", position: "top", fontSize: 10 }} />)}{decision.options.map((option, index) => <Line key={option.id} name={option.name} type="stepAfter" dataKey={`option_${option.id}`} stroke={colors[index % colors.length]} strokeWidth={2.5} dot={count <= 12 ? { r: 3, fill: "white", strokeWidth: 2 } : false} connectNulls={false} isAnimationActive={false} />)}</LineChart></ResponsiveContainer></div> : <div className="cc-empty">Confirm complete charge lists and a planning horizon to plot spending. Missing amounts are not drawn as zero.</div>}
    <details className="cc-detail"><summary>Exact chart values</summary><div className="cc-table-scroll"><table><thead><tr><th>Month</th>{decision.options.map(option => <th key={option.id}>{option.name}</th>)}</tr></thead><tbody>{data.map((row, index) => <tr key={index}><td>{index + 1}</td>{decision.options.map(option => <td key={option.id}>{row[`option_${option.id}`] === null ? "Unknown" : formatMoney(Number(row[`option_${option.id}`]) * 100, decision.currency)}</td>)}</tr>)}</tbody></table></div></details>
    {calculation.breakEven.length > 0 && <div className="cc-break-even"><Target size={18} /><div><h3>Conditions that change the cost comparison</h3>{calculation.breakEven.slice(0, 3).map(point => <p key={`${point.month}-${point.kind}`}><strong>Month {point.month}:</strong> {point.message}</p>)}{calculation.breakEven.length > 3 && <details><summary>{calculation.breakEven.length - 3} later renewal changes</summary>{calculation.breakEven.slice(3).map(point => <p key={`${point.month}-${point.kind}`}>{point.message}</p>)}</details>}</div></div>}
    <p className="cc-hint">Cost crossings compare only the first two options at whole months 1–120. They do not override your requirements or account for an unconfirmed future change.</p>
  </section>;
}

export default function ChoiceApp() {
  const [screen, setScreen] = useState<Screen>("input");
  const [decision, setDecision] = useState<ChoiceDecision | null>(null);
  const decisionRef = useRef(decision); decisionRef.current = decision;
  const [currencyNotice, setCurrencyNotice] = useState("");
  const [change, setChange] = useState<Change | null>(null);
  const [analyses, setAnalyses] = useState<Record<string, MaterialAnalysis>>({});
  const [materialBusy, setMaterialBusy] = useState<Record<string, boolean>>({});
  const [materialErrors, setMaterialErrors] = useState<Record<string, string>>({});
  const materialRequests = useRef<Record<string, AbortController>>({});
  const calculation = useMemo(() => decision ? calculateChoice(decision) : null, [decision]);
  useEffect(() => { document.title = "Clear Choice · Make room for a better decision"; return () => { Object.values(materialRequests.current).forEach(controller => controller.abort()); }; }, []);
  const navigate = (next: Screen) => { setScreen(next); window.scrollTo({ top: 0, behavior: "instant" }); };
  const load = (next: ChoiceDecision, nextScreen: Screen = "review") => { Object.values(materialRequests.current).forEach(controller => controller.abort()); materialRequests.current = {}; decisionRef.current = next; setDecision(next); setChange(null); setCurrencyNotice(""); setAnalyses({}); setMaterialBusy({}); setMaterialErrors({}); navigate(nextScreen); };
  const edit: EditDecision = (label, updater, optionId) => {
    const previous = decisionRef.current; if (!previous) return;
    const next = structuredClone(previous); updater(next); next.version = previous.version + 1;
    decisionRef.current = next; setChange({ label, optionId, before: calculateChoice(previous), previousDecision: previous }); setDecision(next);
  };
  const undo = () => { if (!change || !decision) return; const previous = { ...structuredClone(change.previousDecision), version: decision.version + 1 }; decisionRef.current = previous; setDecision(previous); setChange(null); setCurrencyNotice(""); };
  const materialAnalysis = async (optionId: string) => {
    const snapshot = decisionRef.current; if (!snapshot) return;
    const option = snapshot.options.find(item => item.id === optionId); if (!option?.materials.some(material => material.text.trim())) return;
    materialRequests.current[optionId]?.abort(); const controller = new AbortController(); materialRequests.current[optionId] = controller;
    setMaterialBusy(previous => ({ ...previous, [optionId]: true })); setMaterialErrors(previous => ({ ...previous, [optionId]: "" }));
    try {
      const result = await analyzeMaterials(snapshot, optionId, controller.signal);
      if (controller.signal.aborted || decisionRef.current?.id !== snapshot.id) return;
      if (decisionRef.current.version !== snapshot.version) { setMaterialErrors(previous => ({ ...previous, [optionId]: "Your decision changed while this analysis was running. The response was not applied. Analyze the current version again." })); return; }
      setAnalyses(previous => ({ ...previous, [optionId]: result }));
    } catch (error) { if (!controller.signal.aborted) setMaterialErrors(previous => ({ ...previous, [optionId]: error instanceof Error ? error.message : "Material analysis failed. Your text is preserved." })); }
    finally { if (materialRequests.current[optionId] === controller) setMaterialBusy(previous => ({ ...previous, [optionId]: false })); }
  };
  const removeOption = (id: string) => edit("Removed an option", copy => { copy.options = copy.options.filter(option => option.id !== id); copy.factors = copy.factors.map(factor => { const next = { ...factor, optionIds: factor.optionIds.filter(optionId => optionId !== id), values: { ...factor.values } }; delete next.values[id]; return next; }).filter(factor => factor.optionIds.length); if (!copy.factors.some(factor => factor.id === copy.primaryFactorId)) copy.primaryFactorId = null; });
  return <div className="cc-app"><Header screen={screen} onNavigate={navigate} hasDecision={!!decision} />{screen === "input" || !decision || !calculation ? <Entry onLoad={load} existing={decision} onResume={() => navigate("compare")} /> : <main className="cc-wrap cc-workspace">
    <div className="cc-workspace-top"><Button variant="ghost" size="sm" onClick={() => navigate(screen === "review" ? "input" : "review")}><ArrowLeft size={15} />{screen === "review" ? "Back to description" : "Review your inputs"}</Button><div className="cc-wrap-row"><Badge className={decision.mode === "demo" ? "bg-amber-50 text-amber-800" : "bg-blue-50 text-blue-700"}>{modeText[decision.mode]}</Badge><span className="cc-version">Version {decision.version}</span></div></div>
    <div className="cc-page-title"><div><p className="cc-eyebrow">{screen === "review" ? "Make the decision yours" : "Your decision, in perspective"}</p><h1>{decision.title}</h1><p>{decision.description}</p><div className="cc-wrap-row"><Badge>{decision.domain}</Badge><Badge>{decision.decisionType.replaceAll("_", " ")}</Badge><Badge>{decision.template === "general" ? "Open comparison" : `${decision.template} rules`}</Badge><Badge>{decision.currency}</Badge></div></div>{screen === "review" ? <Button variant="blue" onClick={() => navigate("compare")}>Compare my options <ArrowRight size={16} /></Button> : <Button variant="secondary" onClick={() => navigate("review")}><Pencil size={15} /> Edit all details</Button>}</div>
    {decision.mode === "demo" && <div className="cc-demo-note"><Sparkles size={15} /><span>This is a fictional calculation example. All example values and pasted sample materials are invented. Material analysis runs only if you request it.</span></div>}
    {screen === "review" && <details className="cc-detail cc-meta"><summary>Decision title, currency & original input</summary><div className="cc-two-fields"><label className="cc-field"><span>Decision title</span><input aria-label="Decision title" maxLength={250} value={decision.title} onChange={e => edit("Decision title", copy => { copy.title = e.target.value; })} /></label><label className="cc-field"><span>Currency <small>No exchange-rate conversion</small></span><select aria-label="Decision currency" value={decision.currency} onChange={e => { const nextCurrency = e.target.value as Currency; const previousCurrency = decision.currency; edit("Currency changed · re-enter monetary values", copy => { copy.currency = nextCurrency; copy.context.budgetCents = unknownValue(); copy.options.forEach(option => { option.costs.forEach(cost => { cost.amount = unknownValue(); }); option.costsComplete = false; }); copy.factors.forEach(factor => { if (factor.dataType === "money") { factor.unit = nextCurrency; factor.values = Object.fromEntries(Object.keys(factor.values).map(id => [id, unknownValue()])); factor.target = { min: null, max: null, desired: null }; if (factor.purpose === "hard") factor.confirmed = false; } }); }); setCurrencyNotice(`Currency changed from ${previousCurrency} to ${nextCurrency}. Re-enter charges, budget, and monetary factor targets in ${nextCurrency}; no exchange rate was assumed. Use Undo change to restore all previous amounts.`); }}>{["USD", "CNY", "EUR", "GBP", "CAD"].map(currency => <option key={currency}>{currency}</option>)}</select></label></div><label className="cc-field"><span>Decision description</span><textarea aria-label="Decision description" maxLength={4000} rows={2} value={decision.description} onChange={e => edit("Decision description", copy => { copy.description = e.target.value; })} /></label><p className="cc-hint">Original input: {decision.originalInput || "Manual comparison"}. Changing currency clears monetary inputs for re-entry, with one-step undo. It never assumes an exchange rate.</p></details>}
    {currencyNotice && <p role="status" className="cc-warning">{currencyNotice}</p>}
    {screen === "compare" && <section className={`cc-conclusion ${calculation.comparison.status}`} aria-live="polite"><span className="cc-conclusion-icon"><GitCompareArrows size={22} /></span><div><p className="cc-eyebrow">Current comparison</p><h2>{comparisonTitles[calculation.comparison.status]}</h2><p>{calculation.comparison.message}</p>{calculation.comparison.preferredIds.length > 0 && <strong>{decision.options.filter(option => calculation.comparison.preferredIds.includes(option.id)).map(option => option.name).join(" & ")}</strong>}</div><Badge>Requirements → primary preference</Badge></section>}
    {decision.questions.length > 0 && <details className="cc-detail cc-questions" open={screen === "review" ? true : undefined}><summary>Questions that could change this comparison <span>{decision.questions.length} to consider</span></summary><p className="cc-hint">Answer by updating the relevant condition, option, or factor below. These questions are suggestions, not added requirements.</p>{decision.questions.map((question, index) => <div className="cc-row" key={index}><p>{question}</p><Button variant="ghost" size="sm" onClick={() => edit("Dismissed clarification question", copy => { copy.questions.splice(index, 1); })}>Dismiss</Button></div>)}</details>}
    <ContextEditor decision={decision} edit={edit} />
    {change && <div className="cc-change-banner" role="status"><span><span className="cc-dot" /> Last change: <strong>{change.label}</strong> · recalculated locally</span><Button variant="ghost" size="sm" onClick={undo}><RotateCcw size={13} /> Undo change</Button></div>}
    {calculation.issues.some(issue => issue.includes(":")) && <div className="cc-warning" role="alert">{calculation.issues.slice(0, 3).join(" ")}</div>}
    {screen === "review" ? <><DecisionNotes decision={decision} edit={edit} /><FactorSection decision={decision} calculation={calculation} edit={edit} getCurrent={() => decisionRef.current} /><section className="cc-review-options"><div className="cc-section-head"><div><p className="cc-eyebrow">What each choice involves</p><h2>Your options & sources</h2><p>Unknown is different from zero. Check every relevant charge and mark its list complete.</p></div><Button variant="secondary" size="sm" disabled={decision.options.length >= 6} onClick={() => edit("Added an option", copy => { const existingIds = copy.options.map(option => option.id); const id = freshId("option"); copy.options.push({ id, name: `Option ${String.fromCharCode(65 + copy.options.length)}`, description: "", costs: [], costsComplete: false, minutesPerUse: unknownValue(), minutesPerMonth: unknownValue(), materials: [] }); copy.factors.forEach(factor => { if (existingIds.every(optionId => factor.optionIds.includes(optionId))) { factor.optionIds.push(id); if (!factor.ruleId) factor.values[id] = unknownValue(); } }); })}><Plus size={15} /> Add option</Button></div><div className="cc-review-grid">{decision.options.map((option, index) => <Card className="cc-review-card" key={option.id}><OptionEditor option={option} currency={decision.currency} index={index} onRemove={decision.options.length > 2 ? () => removeOption(option.id) : undefined} onChange={(next, label) => edit(label, copy => { copy.options[index] = next; }, option.id)} /><MaterialsPanel decision={decision} option={option} analysis={analyses[option.id]} busy={!!materialBusy[option.id]} error={materialErrors[option.id]} edit={edit} onAnalyze={() => materialAnalysis(option.id)} /></Card>)}</div></section><div className="cc-continue"><div><h3>Ready to see the tradeoffs?</h3><p>You can compare with unknowns. They will stay visible, and you can keep editing.</p></div><Button variant="blue" onClick={() => navigate("compare")}>Compare my options <ArrowRight size={16} /></Button></div></> : <><div className="cc-options-grid">{decision.options.map((option, index) => <OptionCard key={option.id} option={option} decision={decision} result={calculation.options.find(result => result.optionId === option.id)!} index={index} calculation={calculation} edit={edit} change={change} analysis={analyses[option.id]} busy={!!materialBusy[option.id]} error={materialErrors[option.id]} analyze={() => materialAnalysis(option.id)} />)}</div><CostChart decision={decision} calculation={calculation} /><FactorSection decision={decision} calculation={calculation} edit={edit} getCurrent={() => decisionRef.current} /><details className="cc-detail cc-notes-expand"><summary>Your goals & qualitative assumptions <span>Separate from arithmetic</span></summary><DecisionNotes decision={decision} edit={edit} /></details></>}
  </main>}<footer className="cc-footer cc-wrap"><span><GitCompareArrows size={14} /> Clear Choice · Clarity before commitment.</span><span>Working state stays in this tab. Reloading starts fresh. <a href="?legacy=1">Dayfork legacy</a></span></footer></div>;
}
