import type { ChoiceDecision, ChoiceOption, Currency, Factor, Value } from './types';
const missing = (note = 'Not supplied.'): Value => ({ value: null, source: 'unknown', note });
const demo = (value: number | string | boolean, note = 'Fictional demonstration value; replace with your own facts.'): Value => ({ value, source: 'demo', note });
const option = (id: string, name: string): ChoiceOption => ({ id, name, description: '', costs: [], costsComplete: false, minutesPerUse: missing(), minutesPerMonth: missing(), materials: [] });
const factor = (id: string, name: string, ids: string[], currency: Currency, changes: Partial<Factor> = {}): Factor => ({ id, name, reason: 'Compare the same planning horizon.', optionIds: [...ids], dataType: 'money', unit: currency, allowedValues: [], direction: 'minimize', purpose: 'preference', importance: 3, target: { min: null, max: null, desired: null }, values: Object.fromEntries(ids.map((id) => [id, missing('Calculated from option costs.')])), origin: 'demo', confirmed: true, ruleId: 'total_cost', ...changes });
export function makeManualDecision(): ChoiceDecision {
  return { schemaVersion: 2, id: 'manual-choice', version: 0, title: 'My decision', description: 'Add your options, facts and requirements.', originalInput: '', domain: 'general', decisionType: 'compare', template: 'general', currency: 'USD', goals: [], context: { months: missing('Choose how many whole months to compare.'), usesPerMonth: missing('Needed for usage-based costs or time.'), budgetCents: missing('Optional total budget for the horizon.') }, options: [option('option-a', 'Option A'), option('option-b', 'Option B')], factors: [factor('total-cost', 'Total cost', ['option-a', 'option-b'], 'USD', { origin: 'user', confirmed: true }), factor('total-time', 'Tracked time', ['option-a', 'option-b'], 'USD', { dataType: 'duration', unit: 'minutes', ruleId: 'total_time', purpose: 'reference', origin: 'user', confirmed: true })], primaryFactorId: null, questions: [], assumptions: [], mode: 'manual' };
}
export function makeDemo(kind: 'gym' | 'housing' | 'laptop' | 'course'): ChoiceDecision {
  const base = makeManualDecision(); base.id = `demo-${kind}`; base.mode = 'demo';
  base.assumptions = ['All example details are fictional demonstration data, not model analysis or verified offers.'];
  if (kind === 'gym') {
    const annual = option('annual', 'Annual membership'), monthly = option('monthly', 'Monthly membership'), ids = ['annual', 'monthly'];
    annual.description = 'Annual fee is paid upfront and renewed for each started year.';
    monthly.description = 'Pay only for the months used; identical service and unlimited visits.';
    annual.costs = [{ id: 'membership', name: 'Annual membership', cadence: 'annual', amount: demo(120000) }];
    monthly.costs = [{ id: 'membership', name: 'Monthly membership', cadence: 'monthly', amount: demo(15000) }];
    [annual, monthly].forEach((o) => { o.costsComplete = true; o.minutesPerUse = demo(60); o.minutesPerMonth = demo(0); });
    return { ...base, title: 'Annual or monthly gym membership?', description: 'Identical service, unlimited visits, and no other fees. Compare actual payments.', originalInput: 'Compare an annual gym membership costing CNY 1,200 with a monthly membership costing CNY 150 for 4 months.', domain: 'fitness', decisionType: 'choose_one', template: 'subscription', currency: 'CNY', context: { months: demo(4), usesPerMonth: demo(12, 'Fictional plan: 3 visits weekly, using a 4-week planning month.'), budgetCents: missing() }, options: [annual, monthly], factors: [factor('total-cost', 'Total cost', ids, 'CNY'), factor('first-payment', 'Initial cash needed', ids, 'CNY', { ruleId: 'first_payment', purpose: 'reference', reason: 'Upfront annual payment changes initial cash needs.' }), factor('exit-flexibility', 'Can stop after a month', ids, 'CNY', { dataType: 'boolean', unit: '', direction: 'target', target: { min: null, max: null, desired: true }, ruleId: undefined, values: { annual: demo(false), monthly: demo(true) }, reason: 'A changing plan may make cancellation terms relevant.' }), factor('cost-per-use', 'Cost per visit', ids, 'CNY', { ruleId: 'cost_per_use', purpose: 'reference', reason: 'Visits change unit cost without changing unlimited-membership total-cost ranking.' })], primaryFactorId: 'total-cost', assumptions: [...base.assumptions, 'Same service and unlimited visits. No other fees, refunds, or cancellation charges. Frequency is a planning estimate, not a prediction.'] };
  }
  if (kind === 'housing') {
    const near = option('near', 'Near campus'), far = option('far', 'Farther apartment'), ids = ['near', 'far'];
    near.costs = [{ id: 'rent', name: 'Rent', cadence: 'monthly', amount: demo(150000) }, { id: 'move', name: 'Moving cost', cadence: 'one_time', amount: demo(20000) }];
    far.costs = [{ id: 'rent', name: 'Rent', cadence: 'monthly', amount: demo(110000) }, { id: 'move', name: 'Moving cost', cadence: 'one_time', amount: demo(10000) }];
    near.minutesPerUse = demo(10); far.minutesPerUse = demo(40);
    [near, far].forEach((o) => { o.costsComplete = true; o.minutesPerMonth = demo(0); });
    near.materials = [{ id: 'near-listing', title: 'Example listing', text: 'Rent is $1,500 per month. Cats are welcome. Apply today: only one apartment remains.' }, { id: 'near-chat', title: 'Example leasing chat', text: 'Cats are welcome, subject to written approval. The moving service costs $200.' }];
    far.materials = [{ id: 'far-listing', title: 'Example listing', text: 'Rent is $1,100 per month. Please ask the office about pets. Moving service costs $100.' }];
    return { ...base, title: 'Two apartments and an early class', description: 'Compare rent, cash needs, commute and a confirmed pet requirement.', domain: 'housing', decisionType: 'choose_one', template: 'housing', context: { months: demo(12), usesPerMonth: demo(40, '20 campus days, two one-way trips daily.'), budgetCents: demo(2000000) }, options: [near, far], factors: [factor('total-cost', 'Total cost', ids, 'USD'), factor('commute-time', 'Monthly commute time', ids, 'USD', { dataType: 'duration', unit: 'minutes', ruleId: 'monthly_time', reason: 'Early classes make the time needed to reach campus relevant.' }), factor('pets', 'Cats allowed', ids, 'USD', { dataType: 'boolean', unit: '', direction: 'target', purpose: 'hard', importance: 5, target: { min: null, max: null, desired: true }, ruleId: undefined, values: { near: demo(true), far: missing('Ask the leasing office about pets.') }, reason: 'A home must accommodate a cat in this fictional example.' })], primaryFactorId: 'commute-time', questions: ['Does the farther apartment allow your cat?'], assumptions: [...base.assumptions, 'Rent and moving are the only example costs. Each commute is one way. Example materials have not been analyzed by AI.'] };
  }
  if (kind === 'laptop') {
    const repair = option('repair', 'Repair current laptop'), replace = option('replace', 'Buy a new laptop'), ids = ['repair', 'replace'];
    repair.costs = [{ id: 'purchase', name: 'Repair quote', cadence: 'one_time', amount: demo(18000) }];
    replace.costs = [{ id: 'purchase', name: 'New laptop', cadence: 'one_time', amount: demo(90000) }];
    [repair, replace].forEach((o) => { o.costsComplete = true; o.minutesPerUse = demo(0, 'No routine time difference is assumed.'); o.minutesPerMonth = demo(0); });
    return { ...base, title: 'Repair or replace my laptop?', description: 'Compare a quoted repair and a new device without predicting future reliability.', domain: 'consumer', decisionType: 'repair_or_replace', template: 'purchase', context: { months: demo(12), usesPerMonth: missing(), budgetCents: demo(100000) }, options: [repair, replace], factors: [factor('total-cost', 'Total cost', ids, 'USD'), factor('ready-date', 'Ready to use', ids, 'USD', { dataType: 'date', unit: '', ruleId: undefined, direction: 'minimize', reason: 'Readiness may affect your next project.', values: { repair: demo('2026-09-23'), replace: demo('2026-09-21') } }), factor('workload', 'Workload fit', ids, 'USD', { dataType: 'category', unit: '', ruleId: undefined, direction: 'maximize', allowedValues: ['Basic', 'Good', 'Excellent'], values: { repair: demo('Good'), replace: demo('Excellent') }, reason: 'Fictional user-supplied grades in an explicit order, not model-invented performance scores.' }), factor('reliability', 'Future reliability', ids, 'USD', { dataType: 'text', unit: '', ruleId: undefined, direction: 'none', purpose: 'reference', values: { repair: missing(), replace: missing() }, reason: 'Neither option guarantees future reliability.' })], primaryFactorId: 'total-cost' };
  }
  const evening = option('evening', 'Evening seminar'), selfPaced = option('self-paced', 'Self-paced course'), ids = ['evening', 'self-paced'];
  return { ...base, title: 'Which course fits my plans?', description: 'A generic comparison with missing facts. No course template is required.', domain: 'learning', decisionType: 'choose_one', template: 'general', context: { months: demo(3), usesPerMonth: missing(), budgetCents: missing() }, options: [evening, selfPaced], factors: [factor('total-cost', 'Total cost', ids, 'USD'), factor('study-time', 'Monthly study time', ids, 'USD', { dataType: 'duration', unit: 'minutes', ruleId: 'monthly_time', reason: 'Study needs to fit around other commitments.' }), factor('schedule', 'Schedule fit', ids, 'USD', { dataType: 'text', unit: '', direction: 'none', purpose: 'reference', ruleId: undefined, values: { evening: missing(), 'self-paced': missing() }, reason: 'Supply the timetable and the plans you need to protect.' })], primaryFactorId: 'total-cost', questions: ['What does each course cost?', 'How much study time does each require?', 'Which existing plans must the schedule fit?'] };
}
